### ISSUE TITLE
Failing when destination folder does not exist

### ISSUE THREAD

**Issue by ttben** [FlorianBourniquel/Fenrir#23]
Executing the following when the `~/Desktop/tmppython` folder does not exist, fails with a not-so-clear error 

``` 
python Mining.py https://github.com/jonasoreland/runnerup ~/Desktop/tmppython 1 1 -commitMode
Traceback (most recent call last):
  File "Mining.py", line 160, in <module>
    clone_commit(args.url)
  File "Mining.py", line 69, in clone_commit
    number = len(os.walk(path).__next__()[1])
StopIteration
```

**Comment by ttben** [comment]
Follow:

If you actually create the folder, the Mining fails anyway and I dont understand why
Is it because of `git-lfs` not found? Is it something that I have to manually install?



```
python Mining.py https://github.com/jonasoreland/runnerup ~/Desktop/tmppython 1 1 -commitMode
cloning https://github.com/jonasoreland/runnerup

Traceback (most recent call last):
  File "Mining.py", line 160, in <module>
    clone_commit(args.url)
  File "Mining.py", line 71, in clone_commit
    repo = Repo.clone_from(url, path + "tmp")
  File "/usr/local/lib/python3.7/site-packages/git/repo/base.py", line 988, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/git/repo/base.py", line 939, in _clone
    finalize_process(proc, stderr=stderr)
  File "/usr/local/lib/python3.7/site-packages/git/util.py", line 333, in finalize_process
    proc.wait(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/git/cmd.py", line 415, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v https://github.com/jonasoreland/runnerup /Users/bennibenjamin/Desktop/tmppython/tmp
  stderr: 'Cloning into '/Users/bennibenjamin/Desktop/tmppython/tmp'...
POST git-upload-pack (gzip 3045 to 1602 bytes)
git-lfs filter-process: git-lfs: command not found
fatal: The remote end hung up unexpectedly
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

'
```

Thanks!

**Comment by ttben** [comment]
It was indeed a `git-lfs` missing issue.
Did I missed a needed-dependency ?

**Comment by FlorianBourniquel** [comment]
No It's just that your repo use an additional library git-lfs
