### ISSUE TITLE
Unable to access jarfile ../../libs/Paprika.jar

### ISSUE THREAD

**Issue by ttben** [FlorianBourniquel/Fenrir#24]
I run the following command

`python ./Analyse.py ~/Desktop/tmppython/ ~/Desktop/tmpout/` 

and the output was (I omit the whole build phase)

```
BUILD SUCCESSFUL in 1m 15s
127 actionable tasks: 127 executed
/Users/bennibenjamin/Desktop/tmppython/1
Analyzing all apps in folder /Users/bennibenjamin/Desktop/tmpout/apk/
No apk-properties.json found.
Analyzing jonasoreland_runnerup-9d83a81.apk
Collecting metrics
Saving into database /Users/bennibenjamin/Desktop/tmpout/db/
Done
[9d83a81 1534281928 {}]
Error: Unable to access jarfile ../../libs/Paprika.jar
```

My `pwd` is the root of the `Fenrir` project. What am I doing wrong ?

**Comment by FlorianBourniquel** [comment]
chmod 777  on Paprika.jar ?

**Comment by ttben** [comment]
Seems not to work

```
benni1:Fenrir bennibenjamin$ ls
Analyse.py			Dockerfile			README.md			__pycache__			libs
AntiPatterns.py			JavaFxRender			Render.py			android-platforms-master	requirements.txt
CleanFile.py			Mining.py			Utils.py			file examples
benni1:Fenrir bennibenjamin$ chmod 777 libs/Paprika.jar
benni1:Fenrir bennibenjamin$ python ./Analyse.py ~/Desktop/tmppython/ ~/Desktop/tmpout/
Rm /Users/bennibenjamin/Desktop/tmpout/apk/ [Y/n] Y
Rm /Users/bennibenjamin/Desktop/tmpout/db/ [Y/n]
/Users/bennibenjamin/Desktop/tmppython/1
Analyzing all apps in folder /Users/bennibenjamin/Desktop/tmpout/apk/
No apk-properties.json found.
Analyzing jonasoreland_runnerup-9d83a81.apk
Collecting metrics
Saving into database /Users/bennibenjamin/Desktop/tmpout/db/
Done
[9d83a81 1534281928 {}]
Error: Unable to access jarfile ../../libs/Paprika.jar
benni1:Fenrir bennibenjamin$
```

**Comment by FlorianBourniquel** [comment]
Can you execute 
java -jar libs/Paprika.jar -h

**Comment by ttben** [comment]
Expected message shows up 

```
benni1:Fenrir bennibenjamin$ java -jar libs/Paprika.jar -h
usage: paprika [-h] {analyse,query,delete} ...

positional arguments:
  {analyse,query,delete}
    analyse              Analyse an app
    query                Query the database
    delete               Delete apps from the database

named arguments:
  -h, --help             show this help message and exit
Exception in thread "main" java.lang.NullPointerException
	at paprika.launcher.arg.PaprikaArgParser.getSelectedStarter(PaprikaArgParser.java:97)
	at paprika.launcher.PaprikaLauncher.startPaprika(PaprikaLauncher.java:43)
	at paprika.Main.main(Main.java:30)

```

Maybe it is a bad path handling ? Why using relative path ?

NOTE: the NPE is not supposed to happen I guess, but I think it is a different issue right?
